Document: prometheus-node-exporter
Title: Debian prometheus-node-exporter Manual
Author: <insert document author here>
Abstract: This manual describes what prometheus-node-exporter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prometheus-node-exporter/prometheus-node-exporter.sgml.gz

Format: postscript
Files: /usr/share/doc/prometheus-node-exporter/prometheus-node-exporter.ps.gz

Format: text
Files: /usr/share/doc/prometheus-node-exporter/prometheus-node-exporter.text.gz

Format: HTML
Index: /usr/share/doc/prometheus-node-exporter/html/index.html
Files: /usr/share/doc/prometheus-node-exporter/html/*.html
