Document: prometheus-openvpn-exporter
Title: Debian prometheus-openvpn-exporter Manual
Author: <insert document author here>
Abstract: This manual describes what prometheus-openvpn-exporter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prometheus-openvpn-exporter/prometheus-openvpn-exporter.sgml.gz

Format: postscript
Files: /usr/share/doc/prometheus-openvpn-exporter/prometheus-openvpn-exporter.ps.gz

Format: text
Files: /usr/share/doc/prometheus-openvpn-exporter/prometheus-openvpn-exporter.text.gz

Format: HTML
Index: /usr/share/doc/prometheus-openvpn-exporter/html/index.html
Files: /usr/share/doc/prometheus-openvpn-exporter/html/*.html
