global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'sb.stumasov.ru'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
  - "prometheus_rules.yml"



scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 15s    
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets:
        - localhost:9100
        - ca:9100
        - gw:9100

  - job_name: nginx
    static_configs:
      - targets:
        - localhost:9113

  - job_name: nginxlog
    static_configs:
      - targets:
        - localhost:4040

  #- job_name: mysql
  #  static_configs:
  #    - targets:
  #      - host1.site.local:9104
 
