Document: openvpn-conf
Title: Debian openvpn-conf Manual
Author: <insert document author here>
Abstract: This manual describes what openvpn-conf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openvpn-conf/openvpn-conf.sgml.gz

Format: postscript
Files: /usr/share/doc/openvpn-conf/openvpn-conf.ps.gz

Format: text
Files: /usr/share/doc/openvpn-conf/openvpn-conf.text.gz

Format: HTML
Index: /usr/share/doc/openvpn-conf/html/index.html
Files: /usr/share/doc/openvpn-conf/html/*.html
