Document: prometheus-mysqld-exporter
Title: Debian prometheus-mysqld-exporter Manual
Author: <insert document author here>
Abstract: This manual describes what prometheus-mysqld-exporter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prometheus-mysqld-exporter/prometheus-mysqld-exporter.sgml.gz

Format: postscript
Files: /usr/share/doc/prometheus-mysqld-exporter/prometheus-mysqld-exporter.ps.gz

Format: text
Files: /usr/share/doc/prometheus-mysqld-exporter/prometheus-mysqld-exporter.text.gz

Format: HTML
Index: /usr/share/doc/prometheus-mysqld-exporter/html/index.html
Files: /usr/share/doc/prometheus-mysqld-exporter/html/*.html
