Document: prometheus
Title: Debian prometheus Manual
Author: <insert document author here>
Abstract: This manual describes what prometheus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prometheus/prometheus.sgml.gz

Format: postscript
Files: /usr/share/doc/prometheus/prometheus.ps.gz

Format: text
Files: /usr/share/doc/prometheus/prometheus.text.gz

Format: HTML
Index: /usr/share/doc/prometheus/html/index.html
Files: /usr/share/doc/prometheus/html/*.html
