Document: prometheus-alertmanager
Title: Debian prometheus-alertmanager Manual
Author: <insert document author here>
Abstract: This manual describes what prometheus-alertmanager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prometheus-alertmanager/prometheus-alertmanager.sgml.gz

Format: postscript
Files: /usr/share/doc/prometheus-alertmanager/prometheus-alertmanager.ps.gz

Format: text
Files: /usr/share/doc/prometheus-alertmanager/prometheus-alertmanager.text.gz

Format: HTML
Index: /usr/share/doc/prometheus-alertmanager/html/index.html
Files: /usr/share/doc/prometheus-alertmanager/html/*.html
