Document: prometheus-nginx-exporter
Title: Debian prometheus-nginx-exporter Manual
Author: <insert document author here>
Abstract: This manual describes what prometheus-nginx-exporter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prometheus-nginx-exporter/prometheus-nginx-exporter.sgml.gz

Format: postscript
Files: /usr/share/doc/prometheus-nginx-exporter/prometheus-nginx-exporter.ps.gz

Format: text
Files: /usr/share/doc/prometheus-nginx-exporter/prometheus-nginx-exporter.text.gz

Format: HTML
Index: /usr/share/doc/prometheus-nginx-exporter/html/index.html
Files: /usr/share/doc/prometheus-nginx-exporter/html/*.html
