Document: bkp-srv
Title: Debian bkp-srv Manual
Author: <insert document author here>
Abstract: This manual describes what bkp-srv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bkp-srv/bkp-srv.sgml.gz

Format: postscript
Files: /usr/share/doc/bkp-srv/bkp-srv.ps.gz

Format: text
Files: /usr/share/doc/bkp-srv/bkp-srv.text.gz

Format: HTML
Index: /usr/share/doc/bkp-srv/html/index.html
Files: /usr/share/doc/bkp-srv/html/*.html
