Document: prometheus-nginxlog-exporter
Title: Debian prometheus-nginxlog-exporter Manual
Author: <insert document author here>
Abstract: This manual describes what prometheus-nginxlog-exporter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter.sgml.gz

Format: postscript
Files: /usr/share/doc/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter.ps.gz

Format: text
Files: /usr/share/doc/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter.text.gz

Format: HTML
Index: /usr/share/doc/prometheus-nginxlog-exporter/html/index.html
Files: /usr/share/doc/prometheus-nginxlog-exporter/html/*.html
