Document: file-bkp
Title: Debian file-bkp Manual
Author: <insert document author here>
Abstract: This manual describes what file-bkp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/file-bkp/file-bkp.sgml.gz

Format: postscript
Files: /usr/share/doc/file-bkp/file-bkp.ps.gz

Format: text
Files: /usr/share/doc/file-bkp/file-bkp.text.gz

Format: HTML
Index: /usr/share/doc/file-bkp/html/index.html
Files: /usr/share/doc/file-bkp/html/*.html
